language: python
python:
    - 2.7
    - 3.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:  
  - pip install nose
  - pip install coverage
  - pip install python-coveralls
  - pip install matplotlib

script:
  - python setup.py install
  - nosetests -v --with-coverage pylatt

after_success:
  - coveralls
